sudo: required
services:
  - docker

before_install:
  - docker build -t phytopius/complexnotworking -f ./client/Dockerfile.dev ./client

script:
  - docker run phytopius/complexnotworking npm test -- --coverage

after_success:
  - docker build -t phytopius/multi-client ./client
  - docker build -t phytopius/multi-server ./server
  - docker build -t phytopius/multi-worker ./worker
  - docker build -t phytopius/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push phytopius/multi-client
  - docker push phytopius/multi-server
  - docker push phytopius/multi-worker
  - docker push phytopius/multi-nginx